[common]
api_mode = false
access_token =
default_url =
insert_url =
exclude_remark =
include_remark =
external_config =
base_path = ./base

[node_pref]
udp = false
tcp_fast_open = false
skip_cert_verify = false
sort = false
append_type = false
new_field_name = false
add_emoji = false
remove_old_emoji = false

[server]
listen = 0.0.0.0
port = 25500

[emojis]
# Example: 🇭🇰 = 香港|HK|Hong Kong
# 🇯🇵 = 日本|JP|Japan
# 🇺🇸 = 美国|US|United States
# 🇸🇬 = 新加坡|SG|Singapore
# 🇹🇼 = 台湾|TW|Taiwan
# 🇬🇧 = 英国|UK|United Kingdom

[rename_remarks]
# Example: (.*) - 搬瓦工 = $1 - Bandwagon

[proxy_groups]
# Example: Proxy = select@.*
# Example: Auto = url-test@.*@http://www.gstatic.com/generate_204@300

[rulesets]
# Example: DOMAIN-SUFFIX,google.com,Proxy = https://example.com/rules.txt@3600
